name: build

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        rust: [stable, nightly, beta]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: clippy
        override: true

    - name: Debug build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets --all-features

    - name: Release build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-targets --all-features

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test

  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: rustfmt
        override: true

    - name: Check formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Install Stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate runtimes from doctests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --doc

    - name: Generate docs
      run: ./createDocs.ps1

    - name: Publish the docs as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: target/doc

    - name: Publish the docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc
